"""
TrafficVision India & International Streaming Feeds & Profile Config
Matches https://trafficvision.live/?country=India streaming architecture
"""

TRAFFICVISION_STREAM_SETTINGS = {
    "engine": "Hls.js + HTML5 Direct Video",
    "hls": {
        "enableWorker": True,
        "lowLatencyMode": True,
        "backBufferLength": 30,
        "maxBufferSize": 31457280,  # 30 MB
        "maxBufferLength": 30,
        "manifestLoadingTimeOut": 10000,
        "manifestLoadingMaxRetry": 4,
        "levelLoadingTimeOut": 10000,
        "levelLoadingMaxRetry": 4,
        "fragLoadingTimeOut": 20000,
        "fragLoadingMaxRetry": 6,
        "liveSyncDurationCount": 3,
        "liveMaxLatencyDurationCount": 6,
    },
    "directVideo": {
        "autoPlay": True,
        "playsInline": True,
        "muted": True,
        "loop": True,
        "cacheBustIntervalMs": 180000,
    },
    "reconnect": {
        "baseMs": 2000,
        "maxMs": 30000,
        "formula": "min(baseMs * (2 ** (retry - 1)), maxMs)",
    },
}

TRAFFICVISION_INDIA_FEEDS = [
    {
        "id": "tv-in-delhi-01",
        "name": "Delhi NH-48 Express Corridor",
        "location": "New Delhi, Delhi NCR",
        "state": "Delhi",
        "country": "India",
        "country_code": "IN",
        "category": "High-Density Highway",
        "feed_type": "video",
        "stream_type": "direct",
        "stream_url": "https://assets.mixkit.co/videos/preview/mixkit-traffic-at-a-busy-intersection-in-delhi-42358-large.mp4",
        "backup_stream_url": "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
        "fps": 30,
        "resolution": "1080p FHD",
        "speed_limit": 80,
        "coordinates": [28.6139, 77.2090],
        "is_live": True,
        "viewers": 1420,
    },
    {
        "id": "tv-in-mumbai-01",
        "name": "Mumbai Bandra-Worli Sea Link",
        "location": "Mumbai, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "country_code": "IN",
        "category": "Coastal Expressway",
        "feed_type": "video",
        "stream_type": "direct",
        "stream_url": "https://assets.mixkit.co/videos/preview/mixkit-cars-moving-on-a-highway-at-night-42385-large.mp4",
        "fps": 60,
        "resolution": "1080p 60FPS",
        "speed_limit": 100,
        "coordinates": [19.0368, 72.8172],
        "is_live": True,
        "viewers": 2890,
    },
    {
        "id": "tv-in-blr-01",
        "name": "Bengaluru Silk Board - ORR Flyway",
        "location": "Bengaluru, Karnataka",
        "state": "Karnataka",
        "country": "India",
        "country_code": "IN",
        "category": "Urban Arterial",
        "feed_type": "video",
        "stream_type": "direct",
        "stream_url": "https://assets.mixkit.co/videos/preview/mixkit-traffic-in-a-busy-city-at-dusk-42416-large.mp4",
        "fps": 30,
        "resolution": "1080p FHD",
        "speed_limit": 60,
        "coordinates": [12.9176, 77.6238],
        "is_live": True,
        "viewers": 3105,
    },
    {
        "id": "tv-in-goa-01",
        "name": "Goa Panaji Mandovi Bridge",
        "location": "Panaji, Goa",
        "state": "Goa",
        "country": "India",
        "country_code": "IN",
        "category": "River Transit",
        "feed_type": "hls",
        "stream_type": "hls",
        "stream_url": "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
        "fps": 30,
        "resolution": "720p HD",
        "speed_limit": 70,
        "coordinates": [15.4989, 73.8278],
        "is_live": True,
        "viewers": 940,
    },
    {
        "id": "tv-in-varanasi-01",
        "name": "Varanasi Ghats Heritage Corridor",
        "location": "Varanasi, Uttar Pradesh",
        "state": "Uttar Pradesh",
        "country": "India",
        "country_code": "IN",
        "category": "Pedestrian & Urban",
        "feed_type": "video",
        "stream_type": "direct",
        "stream_url": "https://assets.mixkit.co/videos/preview/mixkit-busy-street-market-in-an-indian-city-42434-large.mp4",
        "fps": 30,
        "resolution": "1080p FHD",
        "speed_limit": 30,
        "coordinates": [25.3176, 82.9739],
        "is_live": True,
        "viewers": 1870,
    },
    {
        "id": "tv-in-kolkata-01",
        "name": "Kolkata EM Bypass Expressway",
        "location": "Kolkata, West Bengal",
        "state": "West Bengal",
        "country": "India",
        "country_code": "IN",
        "category": "Expressway",
        "feed_type": "video",
        "stream_type": "direct",
        "stream_url": "https://assets.mixkit.co/videos/preview/mixkit-traffic-moving-on-a-wide-highway-42417-large.mp4",
        "fps": 30,
        "resolution": "1080p FHD",
        "speed_limit": 70,
        "coordinates": [22.5726, 88.3639],
        "is_live": True,
        "viewers": 1120,
    },
    {
        "id": "tv-in-hyd-01",
        "name": "Hyderabad HITEC City Cyber Towers",
        "location": "Hyderabad, Telangana",
        "state": "Telangana",
        "country": "India",
        "country_code": "IN",
        "category": "IT District Junction",
        "feed_type": "video",
        "stream_type": "direct",
        "stream_url": "https://assets.mixkit.co/videos/preview/mixkit-traffic-on-a-busy-intersection-42420-large.mp4",
        "fps": 60,
        "resolution": "1080p 60FPS",
        "speed_limit": 60,
        "coordinates": [17.4474, 78.3762],
        "is_live": True,
        "viewers": 2240,
    },
    {
        "id": "tv-in-chennai-01",
        "name": "Chennai Anna Salai Arterial",
        "location": "Chennai, Tamil Nadu",
        "state": "Tamil Nadu",
        "country": "India",
        "country_code": "IN",
        "category": "Central Corridor",
        "feed_type": "video",
        "stream_type": "direct",
        "stream_url": "https://assets.mixkit.co/videos/preview/mixkit-cars-driving-on-a-highway-during-rush-hour-42418-large.mp4",
        "fps": 30,
        "resolution": "1080p FHD",
        "speed_limit": 60,
        "coordinates": [13.0827, 80.2707],
        "is_live": True,
        "viewers": 1560,
    },
    {
        "id": "tv-bpjt-01",
        "name": "Jasa Marga Trans-Java Highway KM 582",
        "location": "Sragen - Ngawi Corridor",
        "state": "Java",
        "country": "TrafficVision Live HLS",
        "country_code": "ID",
        "category": "Live HLS Tollway",
        "feed_type": "hls",
        "stream_type": "hls",
        "stream_url": "https://jmlive.jasamarga.com/hls/16/6b23383c-c0aa-4587-b1c8-765606393fe3/index.m3u8",
        "backup_stream_url": "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
        "fps": 25,
        "resolution": "720p HLS",
        "speed_limit": 100,
        "coordinates": [-7.428, 111.025],
        "is_live": True,
        "viewers": 850,
    }
]
