/**
 * TrafficVision Catalog & Stream Definitions
 * High-performance, zero-latency video streams matching https://trafficvision.live/?country=India
 */

export const TRAFFIC_VISION_SETTINGS = {
  hls: {
    enableWorker: true,
    lowLatencyMode: true,
    backBufferLength: 30,
    maxBufferSize: 30 * 1024 * 1024,
    manifestLoadingTimeOut: 10000,
    fragLoadingTimeOut: 20000,
  },
  directVideo: {
    autoPlay: true,
    playsInline: true,
    muted: true,
    loop: true,
  }
};

export const INDIA_TRAFFIC_CAMERAS = [
  {
    id: 'tv-in-mumbai-01',
    name: 'Mumbai Bandra-Worli Sea Link',
    location: 'Mumbai, Maharashtra',
    state: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    category: 'Coastal Expressway',
    feedType: 'video',
    streamType: 'direct',
    streamUrl: '/videos/mumbai_traffic.mp4',
    backupStreamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    fps: 60,
    resolution: '1080p 60FPS',
    speedLimit: 100,
    coordinates: [19.0368, 72.8172],
    gps: '19.0368° N, 72.8172° E',
    isLive: true,
    viewers: 2890,
    description: 'Live traffic monitoring of the 8-lane cable-stayed bridge over Arabian Sea.',
  },
  {
    id: 'tv-in-delhi-01',
    name: 'Delhi NH-48 Express Corridor',
    location: 'New Delhi, Delhi NCR',
    state: 'Delhi',
    country: 'India',
    countryCode: 'IN',
    category: 'High-Density Highway',
    feedType: 'video',
    streamType: 'direct',
    streamUrl: '/videos/delhi_traffic.mp4',
    backupStreamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    fps: 30,
    resolution: '1080p FHD',
    speedLimit: 80,
    coordinates: [28.6139, 77.2090],
    gps: '28.6139° N, 77.2090° E',
    isLive: true,
    viewers: 1420,
    description: 'Surveillance along NH-48 towards IGI Airport & Gurugram corridor.',
  },
  {
    id: 'tv-in-blr-01',
    name: 'Bengaluru Silk Board - ORR Flyway',
    location: 'Bengaluru, Karnataka',
    state: 'Karnataka',
    country: 'India',
    countryCode: 'IN',
    category: 'Urban Arterial',
    feedType: 'video',
    streamType: 'direct',
    streamUrl: '/videos/bangalore_traffic.mp4',
    fps: 30,
    resolution: '1080p FHD',
    speedLimit: 60,
    coordinates: [12.9176, 77.6238],
    gps: '12.9176° N, 77.6238° E',
    isLive: true,
    viewers: 3105,
    description: 'Outer Ring Road tech corridor with vehicle classification.',
  },
  {
    id: 'tv-in-goa-01',
    name: 'Goa Panaji Mandovi Bridge',
    location: 'Panaji, Goa',
    state: 'Goa',
    country: 'India',
    countryCode: 'IN',
    category: 'River Transit',
    feedType: 'video',
    streamType: 'direct',
    streamUrl: '/videos/goa_traffic.mp4',
    fps: 30,
    resolution: '720p HD',
    speedLimit: 70,
    coordinates: [15.4989, 73.8278],
    gps: '15.4989° N, 73.8278° E',
    isLive: true,
    viewers: 940,
    description: 'Mandovi river bridge linking North & South Goa highway corridors.',
  },
  {
    id: 'tv-in-hls-live',
    name: 'National Highway HLS High-Throughput Stream',
    location: 'National Highway Corridor',
    state: 'Live HLS',
    country: 'India',
    countryCode: 'IN',
    category: 'Live HLS Feed',
    feedType: 'hls',
    streamType: 'hls',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    fps: 30,
    resolution: '1080p HLS',
    speedLimit: 90,
    coordinates: [20.5937, 78.9629],
    gps: '20.5937° N, 78.9629° E',
    isLive: true,
    viewers: 1980,
    description: 'Low-latency HLS video stream with worker acceleration.',
  }
];
